[package]
name = "vm-client"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]
edition = "2018"
description = "GToolkit VM"

[[bin]]
name = "vm_client"
path = "src/main.rs"

[dependencies]
vm-bindings = { path = "../vm-bindings" }
nfd = {  git = "https://github.com/saurvs/nfd-rs.git", rev = "07578c5fea4d7b1f35fbf128f04b6264c3bf3c5a" }
clap = "3.0.0-beta.2"

[build-dependencies]
embed-resource = "1.6"

[profile.release]
rpath = false

[profile.dev]
rpath = false

[profile.test]
rpath = false

[profile.bench]
rpath = false