[package]
name = "vm-client"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]
edition = "2018"
description = "GToolkit VM"

[[bin]]
name = "vm_client"
path = "src/main.rs"

[[bin]]
name = "vm_client-cli"
path = "src/main_cli.rs"

[dependencies]
vm-bindings = { path = "../vm-bindings", default-features = false }
nfd2 = "0.3.0"
clap = "3.0.0-beta.2"
thiserror = "1.0.26"
dirs = "3.0"
log = "0.4"
user-error = "1.2.8"
to_absolute = "0.1.0"

[features]
default = ["full"]
minimal = ["vm-bindings/minimal"]
full = ["vm-bindings/full"]

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.9.1"
libloading = "0.7"
libc = "0.2"

[build-dependencies]
embed-resource = "1.6"

[profile.release]
rpath = false

[profile.dev]
rpath = false

[profile.test]
rpath = false

[profile.bench]
rpath = false