[package]
name = "vm-client"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]
edition = "2018"
description = "GToolkit VM"

[[bin]]
name = "vm_client"
path = "src/main.rs"

[dependencies]
vm-bindings = { path = "../vm-bindings" }
nfd2 = "0.3.0"
clap = "3.0.0-beta.2"

[build-dependencies]
embed-resource = "1.6"

[profile.release]
rpath = false

[profile.dev]
rpath = false

[profile.test]
rpath = false

[profile.bench]
rpath = false