[package]
name = "vm-library-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7"
clap = { version = "3.2", features = [ "derive", "color" ] }